-- Style & Scent Engine: datos iniciales
-- Catálogos (categorías, colores, estilos, familias, notas, estados), reglas
-- de puntuación (sinergias_color, sinergias_estilo, filtros_exclusion) y una
-- colección de ejemplo de prendas y perfumes.
-- Se carga automáticamente tras 01-schema.sql al crear el contenedor por primera vez.
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `categorias` WRITE;
/*!40000 ALTER TABLE `categorias` DISABLE KEYS */;
INSERT INTO `categorias` (`id_categoria`, `nombre`) VALUES (5,'Accesorio');
INSERT INTO `categorias` (`id_categoria`, `nombre`) VALUES (3,'Calzado');
INSERT INTO `categorias` (`id_categoria`, `nombre`) VALUES (2,'Piernas');
INSERT INTO `categorias` (`id_categoria`, `nombre`) VALUES (1,'Torso');
/*!40000 ALTER TABLE `categorias` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `colores` WRITE;
/*!40000 ALTER TABLE `colores` DISABLE KEYS */;
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (5,'Crema');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (1,'Marrón');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (2,'Negro');
/*!40000 ALTER TABLE `colores` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `estados_posesion` WRITE;
/*!40000 ALTER TABLE `estados_posesion` DISABLE KEYS */;
INSERT INTO `estados_posesion` (`id_estado`, `nombre`) VALUES (2,'En camino');
INSERT INTO `estados_posesion` (`id_estado`, `nombre`) VALUES (1,'En coleccion');
INSERT INTO `estados_posesion` (`id_estado`, `nombre`) VALUES (3,'Lista de deseos');
/*!40000 ALTER TABLE `estados_posesion` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `estilos` WRITE;
/*!40000 ALTER TABLE `estilos` DISABLE KEYS */;
INSERT INTO `estilos` (`id_estilo`, `nombre`) VALUES (3,'Casual');
INSERT INTO `estilos` (`id_estilo`, `nombre`) VALUES (1,'Streetwear');
/*!40000 ALTER TABLE `estilos` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `familias_olfativas` WRITE;
/*!40000 ALTER TABLE `familias_olfativas` DISABLE KEYS */;
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (5,'Amaderada Ámbar');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (4,'Amaderada Aromática');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (6,'Amaderada Especiada');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (9,'Ámbar Especiada');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (3,'Ámbar Fougère');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (7,'Aromática Fougère');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (8,'Cítrica Aromática');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (10,'Cuero');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (1,'Fougère Oriental');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (12,'Frutal');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (11,'Gourmand');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (2,'Oriental Amaderada');
/*!40000 ALTER TABLE `familias_olfativas` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `filtros_exclusion` WRITE;
/*!40000 ALTER TABLE `filtros_exclusion` DISABLE KEYS */;
INSERT INTO `filtros_exclusion` (`id_filtro`, `id_nota`, `penalizacion_score`) VALUES (1,5,-100);
/*!40000 ALTER TABLE `filtros_exclusion` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `notas` WRITE;
/*!40000 ALTER TABLE `notas` DISABLE KEYS */;
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (32,'Almizcle');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (22,'Ámbar');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (30,'Azúcar');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (8,'Bergamota');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (23,'Café');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (29,'Canela');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (12,'Caramelo');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (4,'Cardamomo');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (9,'Coco');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (28,'Cuero');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (27,'Especias');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (7,'Haba Tonka');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (5,'Iris');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (20,'Jengibre');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (2,'Lavanda');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (19,'Limón');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (18,'Madera de Ámbar');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (14,'Mandarina');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (25,'Mango');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (17,'Manzana');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (1,'Menta');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (6,'Miel');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (31,'Naranja');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (24,'Nuez moscada');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (26,'Pan de jengibre');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (15,'Pimienta rosa');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (10,'Piña');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (11,'Salvia');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (16,'Sándalo');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (21,'Toffee');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (3,'Vainilla');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (13,'Vetiver');
/*!40000 ALTER TABLE `notas` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `perfume_nota` WRITE;
/*!40000 ALTER TABLE `perfume_nota` DISABLE KEYS */;
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (1,1);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (10,1);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (12,1);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (1,2);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (2,2);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (14,2);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (1,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (2,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (3,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (7,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (13,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (14,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (18,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (19,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (20,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (2,4);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (17,4);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (18,4);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (2,5);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (3,6);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (3,7);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (4,7);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (5,7);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (4,8);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (8,8);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (4,9);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (5,9);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (21,9);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (5,10);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (15,10);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (21,10);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (6,11);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (9,11);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (6,12);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (6,13);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (12,13);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (14,13);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (7,14);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (8,14);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (7,15);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (11,15);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (8,16);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (9,17);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (13,17);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (9,18);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (10,19);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (20,19);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (10,20);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (15,20);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (11,21);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (11,22);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (16,22);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (17,22);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (12,23);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (19,23);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (12,24);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (13,25);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (21,25);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (15,26);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (16,27);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (16,28);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (17,28);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (18,29);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (19,30);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (20,31);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (20,32);
/*!40000 ALTER TABLE `perfume_nota` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `perfumes` WRITE;
/*!40000 ALTER TABLE `perfumes` DISABLE KEYS */;
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (1,'JPG Le Male EDT','Jean Paul Gaultier',1,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (2,'JPG Le Male Le Parfum','Jean Paul Gaultier',2,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (3,'JPG Le Male Elixir','Jean Paul Gaultier',3,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (4,'JPG Le Beau EDT','Jean Paul Gaultier',4,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (5,'JPG Le Beau Le Parfum','Jean Paul Gaultier',5,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (6,'JPG Scandal Pour Homme','Jean Paul Gaultier',5,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (7,'Versace Eros Flame','Versace',6,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (8,'Dior Sauvage Parfum','Dior',3,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (9,'YSL Y EDP','Yves Saint Laurent',7,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (10,'YSL Y Iced Cologne','Yves Saint Laurent',8,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (11,'Emporio Armani Stronger With You Intensely','Emporio Armani',3,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (12,'Givenchy Gentleman Society Extreme','Givenchy',6,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (13,'Gisada Ambassador Men Parfum','Gisada',4,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (14,'Valentino Born in Roma Intense','Valentino',3,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (15,'Valentino Born in Roma Yellow Dream','Valentino',9,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (16,'Vulcan Feu','Vulcan',9,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (17,'Tom Ford Ombré Leather','Tom Ford',10,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (18,'French Avenue Liquid Brun','French Avenue',6,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (19,'Mancera Amore Caffè','Mancera',11,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (20,'Xerjoff Erba Gold','Xerjoff',12,3);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (21,'Lorenzzo Pazzaglia Summer Hammer','Lorenzzo Pazzaglia',12,3);
/*!40000 ALTER TABLE `perfumes` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `prenda_estilo` WRITE;
/*!40000 ALTER TABLE `prenda_estilo` DISABLE KEYS */;
INSERT INTO `prenda_estilo` (`id_prenda`, `id_estilo`) VALUES (1,1);
INSERT INTO `prenda_estilo` (`id_prenda`, `id_estilo`) VALUES (2,1);
INSERT INTO `prenda_estilo` (`id_prenda`, `id_estilo`) VALUES (3,1);
INSERT INTO `prenda_estilo` (`id_prenda`, `id_estilo`) VALUES (4,1);
INSERT INTO `prenda_estilo` (`id_prenda`, `id_estilo`) VALUES (4,3);
/*!40000 ALTER TABLE `prenda_estilo` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `prendas` WRITE;
/*!40000 ALTER TABLE `prendas` DISABLE KEYS */;
INSERT INTO `prendas` (`id_prenda`, `nombre`, `id_categoria`, `id_color`, `fecha_registro`) VALUES (1,'Chaqueta Leon S. Kennedy',1,1,'2026-09-26 11:27:20');
INSERT INTO `prendas` (`id_prenda`, `nombre`, `id_categoria`, `id_color`, `fecha_registro`) VALUES (2,'Pantalón Baggy',2,2,'2026-09-26 11:27:20');
INSERT INTO `prendas` (`id_prenda`, `nombre`, `id_categoria`, `id_color`, `fecha_registro`) VALUES (3,'Adidas Campus Bad Bunny',3,1,'2026-09-26 11:27:20');
INSERT INTO `prendas` (`id_prenda`, `nombre`, `id_categoria`, `id_color`, `fecha_registro`) VALUES (4,'Ray-Ban Meta',5,5,'2026-09-26 12:09:07');
/*!40000 ALTER TABLE `prendas` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `sinergias_color` WRITE;
/*!40000 ALTER TABLE `sinergias_color` DISABLE KEYS */;
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (1,1,10,30);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (2,1,6,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (3,1,9,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (4,1,11,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (5,2,2,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (6,2,10,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (7,2,3,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (8,5,8,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (9,5,4,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (10,5,12,20);
/*!40000 ALTER TABLE `sinergias_color` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `sinergias_estilo` WRITE;
/*!40000 ALTER TABLE `sinergias_estilo` DISABLE KEYS */;
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (1,1,3,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (2,1,11,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (3,1,5,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (4,1,12,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (5,1,7,10);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (6,1,3,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (7,1,11,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (8,1,5,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (9,1,12,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (10,1,7,10);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (11,1,3,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (12,1,11,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (13,1,5,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (14,1,12,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (15,1,7,10);
/*!40000 ALTER TABLE `sinergias_estilo` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

