-- Style & Scent Engine: datos iniciales
-- Catálogos (categorías, colores, estilos, familias, notas, estados), reglas
-- de puntuación (sinergias_color, sinergias_estilo, filtros_exclusion) y una
-- colección de ejemplo de prendas y perfumes.
-- Se carga automáticamente tras 01-schema.sql al crear el contenedor por primera vez.
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `categorias` WRITE;
/*!40000 ALTER TABLE `categorias` DISABLE KEYS */;
INSERT INTO `categorias` (`id_categoria`, `nombre`) VALUES (5,'Accesorio');
INSERT INTO `categorias` (`id_categoria`, `nombre`) VALUES (3,'Calzado');
INSERT INTO `categorias` (`id_categoria`, `nombre`) VALUES (2,'Piernas');
INSERT INTO `categorias` (`id_categoria`, `nombre`) VALUES (1,'Torso');
/*!40000 ALTER TABLE `categorias` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `colores` WRITE;
/*!40000 ALTER TABLE `colores` DISABLE KEYS */;
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (51,'Amarillo');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (43,'Azul');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (44,'Azul claro');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (45,'Azul marino');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (38,'Beige');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (32,'Blanco');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (48,'Burdeos');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (37,'Camel');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (39,'Caqui');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (56,'Coral');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (5,'Crema');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (33,'Gris');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (34,'Gris claro');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (35,'Gris oscuro');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (55,'Lila');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (1,'Marrón');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (36,'Marrón claro');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (52,'Morado');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (53,'Mostaza');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (50,'Naranja');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (2,'Negro');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (47,'Rojo');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (49,'Rosa');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (57,'Terracota');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (54,'Turquesa');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (46,'Vaquero');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (41,'Verde');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (42,'Verde botella');
INSERT INTO `colores` (`id_color`, `nombre`) VALUES (40,'Verde oliva');
/*!40000 ALTER TABLE `colores` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `estados_posesion` WRITE;
/*!40000 ALTER TABLE `estados_posesion` DISABLE KEYS */;
INSERT INTO `estados_posesion` (`id_estado`, `nombre`) VALUES (2,'En camino');
INSERT INTO `estados_posesion` (`id_estado`, `nombre`) VALUES (1,'En coleccion');
INSERT INTO `estados_posesion` (`id_estado`, `nombre`) VALUES (3,'Lista de deseos');
/*!40000 ALTER TABLE `estados_posesion` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `estilos` WRITE;
/*!40000 ALTER TABLE `estilos` DISABLE KEYS */;
INSERT INTO `estilos` (`id_estilo`, `nombre`) VALUES (3,'Casual');
INSERT INTO `estilos` (`id_estilo`, `nombre`) VALUES (13,'Deportivo');
INSERT INTO `estilos` (`id_estilo`, `nombre`) VALUES (12,'Elegante');
INSERT INTO `estilos` (`id_estilo`, `nombre`) VALUES (14,'Minimalista');
INSERT INTO `estilos` (`id_estilo`, `nombre`) VALUES (17,'Preppy');
INSERT INTO `estilos` (`id_estilo`, `nombre`) VALUES (16,'Rockero');
INSERT INTO `estilos` (`id_estilo`, `nombre`) VALUES (1,'Streetwear');
INSERT INTO `estilos` (`id_estilo`, `nombre`) VALUES (19,'Techwear');
INSERT INTO `estilos` (`id_estilo`, `nombre`) VALUES (15,'Vintage');
INSERT INTO `estilos` (`id_estilo`, `nombre`) VALUES (18,'Workwear');
/*!40000 ALTER TABLE `estilos` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `familias_olfativas` WRITE;
/*!40000 ALTER TABLE `familias_olfativas` DISABLE KEYS */;
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (5,'Amaderada Ámbar');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (4,'Amaderada Aromática');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (6,'Amaderada Especiada');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (9,'Ámbar Especiada');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (3,'Ámbar Fougère');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (7,'Aromática Fougère');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (8,'Cítrica Aromática');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (10,'Cuero');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (1,'Fougère Oriental');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (12,'Frutal');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (11,'Gourmand');
INSERT INTO `familias_olfativas` (`id_familia`, `nombre`) VALUES (2,'Oriental Amaderada');
/*!40000 ALTER TABLE `familias_olfativas` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `filtros_exclusion` WRITE;
/*!40000 ALTER TABLE `filtros_exclusion` DISABLE KEYS */;
INSERT INTO `filtros_exclusion` (`id_filtro`, `id_nota`, `penalizacion_score`) VALUES (1,5,-100);
/*!40000 ALTER TABLE `filtros_exclusion` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `notas` WRITE;
/*!40000 ALTER TABLE `notas` DISABLE KEYS */;
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (32,'Almizcle');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (22,'Ámbar');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (30,'Azúcar');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (8,'Bergamota');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (23,'Café');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (29,'Canela');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (12,'Caramelo');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (4,'Cardamomo');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (9,'Coco');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (28,'Cuero');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (27,'Especias');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (7,'Haba Tonka');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (5,'Iris');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (20,'Jengibre');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (2,'Lavanda');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (19,'Limón');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (18,'Madera de Ámbar');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (14,'Mandarina');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (25,'Mango');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (17,'Manzana');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (1,'Menta');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (6,'Miel');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (31,'Naranja');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (24,'Nuez moscada');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (26,'Pan de jengibre');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (15,'Pimienta rosa');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (10,'Piña');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (11,'Salvia');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (16,'Sándalo');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (21,'Toffee');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (3,'Vainilla');
INSERT INTO `notas` (`id_nota`, `nombre`) VALUES (13,'Vetiver');
/*!40000 ALTER TABLE `notas` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `perfume_nota` WRITE;
/*!40000 ALTER TABLE `perfume_nota` DISABLE KEYS */;
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (1,1);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (10,1);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (12,1);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (1,2);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (2,2);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (14,2);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (1,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (2,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (3,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (7,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (13,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (14,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (18,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (19,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (20,3);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (2,4);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (17,4);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (18,4);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (2,5);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (3,6);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (3,7);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (4,7);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (5,7);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (4,8);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (8,8);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (4,9);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (5,9);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (21,9);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (5,10);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (15,10);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (21,10);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (6,11);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (9,11);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (6,12);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (6,13);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (12,13);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (14,13);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (7,14);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (8,14);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (7,15);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (11,15);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (8,16);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (9,17);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (13,17);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (9,18);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (10,19);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (20,19);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (10,20);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (15,20);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (11,21);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (11,22);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (16,22);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (17,22);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (12,23);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (19,23);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (12,24);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (13,25);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (21,25);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (15,26);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (16,27);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (16,28);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (17,28);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (18,29);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (19,30);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (20,31);
INSERT INTO `perfume_nota` (`id_perfume`, `id_nota`) VALUES (20,32);
/*!40000 ALTER TABLE `perfume_nota` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `perfumes` WRITE;
/*!40000 ALTER TABLE `perfumes` DISABLE KEYS */;
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (1,'JPG Le Male EDT','Jean Paul Gaultier',1,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (2,'JPG Le Male Le Parfum','Jean Paul Gaultier',2,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (3,'JPG Le Male Elixir','Jean Paul Gaultier',3,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (4,'JPG Le Beau EDT','Jean Paul Gaultier',4,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (5,'JPG Le Beau Le Parfum','Jean Paul Gaultier',5,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (6,'JPG Scandal Pour Homme','Jean Paul Gaultier',5,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (7,'Versace Eros Flame','Versace',6,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (8,'Dior Sauvage Parfum','Dior',3,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (9,'YSL Y EDP','Yves Saint Laurent',7,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (10,'YSL Y Iced Cologne','Yves Saint Laurent',8,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (11,'Emporio Armani Stronger With You Intensely','Emporio Armani',3,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (12,'Givenchy Gentleman Society Extreme','Givenchy',6,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (13,'Gisada Ambassador Men Parfum','Gisada',4,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (14,'Valentino Born in Roma Intense','Valentino',3,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (15,'Valentino Born in Roma Yellow Dream','Valentino',9,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (16,'Vulcan Feu','Vulcan',9,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (17,'Tom Ford Ombré Leather','Tom Ford',10,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (18,'French Avenue Liquid Brun','French Avenue',6,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (19,'Mancera Amore Caffè','Mancera',11,1);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (20,'Xerjoff Erba Gold','Xerjoff',12,3);
INSERT INTO `perfumes` (`id_perfume`, `nombre`, `marca`, `id_familia`, `id_estado`) VALUES (21,'Lorenzzo Pazzaglia Summer Hammer','Lorenzzo Pazzaglia',12,3);
/*!40000 ALTER TABLE `perfumes` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `prenda_estilo` WRITE;
/*!40000 ALTER TABLE `prenda_estilo` DISABLE KEYS */;
INSERT INTO `prenda_estilo` (`id_prenda`, `id_estilo`) VALUES (1,1);
INSERT INTO `prenda_estilo` (`id_prenda`, `id_estilo`) VALUES (2,1);
INSERT INTO `prenda_estilo` (`id_prenda`, `id_estilo`) VALUES (3,1);
INSERT INTO `prenda_estilo` (`id_prenda`, `id_estilo`) VALUES (4,1);
INSERT INTO `prenda_estilo` (`id_prenda`, `id_estilo`) VALUES (4,3);
/*!40000 ALTER TABLE `prenda_estilo` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `prendas` WRITE;
/*!40000 ALTER TABLE `prendas` DISABLE KEYS */;
INSERT INTO `prendas` (`id_prenda`, `nombre`, `id_categoria`, `id_color`, `fecha_registro`) VALUES (1,'Chaqueta Leon S. Kennedy',1,1,'2026-09-26 11:27:20');
INSERT INTO `prendas` (`id_prenda`, `nombre`, `id_categoria`, `id_color`, `fecha_registro`) VALUES (2,'Pantalón Baggy',2,2,'2026-09-26 11:27:20');
INSERT INTO `prendas` (`id_prenda`, `nombre`, `id_categoria`, `id_color`, `fecha_registro`) VALUES (3,'Adidas Campus Bad Bunny',3,1,'2026-09-26 11:27:20');
INSERT INTO `prendas` (`id_prenda`, `nombre`, `id_categoria`, `id_color`, `fecha_registro`) VALUES (4,'Ray-Ban Meta',5,5,'2026-09-26 12:09:07');
/*!40000 ALTER TABLE `prendas` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `sinergias_color` WRITE;
/*!40000 ALTER TABLE `sinergias_color` DISABLE KEYS */;
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (1,1,10,30);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (2,1,6,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (3,1,9,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (4,1,11,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (5,2,2,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (6,2,10,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (7,2,3,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (8,5,8,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (9,5,4,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (10,5,12,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (88,32,8,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (89,32,7,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (90,32,12,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (91,33,4,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (92,33,7,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (93,33,1,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (94,34,8,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (95,34,7,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (96,34,4,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (97,35,4,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (98,35,1,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (99,35,2,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (100,36,6,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (101,36,9,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (102,36,5,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (103,37,5,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (104,37,9,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (105,37,10,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (106,38,5,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (107,38,9,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (108,38,11,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (109,39,4,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (110,39,6,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (111,39,7,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (112,40,4,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (113,40,6,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (114,40,10,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (115,41,4,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (116,41,7,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (117,41,8,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (118,42,4,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (119,42,2,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (120,42,10,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (121,43,7,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (122,43,8,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (123,43,3,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (124,44,8,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (125,44,12,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (126,44,7,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (127,45,7,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (128,45,8,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (129,45,1,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (130,46,8,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (131,46,7,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (132,46,12,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (133,47,2,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (134,47,9,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (135,47,11,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (136,48,2,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (137,48,9,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (138,48,11,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (139,49,12,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (140,49,11,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (141,49,8,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (142,50,12,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (143,50,8,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (144,50,11,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (145,51,8,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (146,51,12,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (147,52,2,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (148,52,11,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (149,52,12,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (150,53,9,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (151,53,6,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (152,53,11,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (153,54,8,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (154,54,12,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (155,54,7,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (156,55,12,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (157,55,11,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (158,55,1,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (159,56,12,25);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (160,56,8,15);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (161,56,11,10);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (162,57,6,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (163,57,9,20);
INSERT INTO `sinergias_color` (`id_regla`, `id_color`, `id_familia`, `puntos_sumados`) VALUES (164,57,10,10);
/*!40000 ALTER TABLE `sinergias_color` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `sinergias_estilo` WRITE;
/*!40000 ALTER TABLE `sinergias_estilo` DISABLE KEYS */;
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (1,1,3,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (2,1,11,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (3,1,5,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (4,1,12,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (5,1,7,10);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (45,12,2,25);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (46,12,10,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (47,12,6,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (48,12,1,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (49,13,8,25);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (50,13,7,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (51,13,12,10);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (52,14,4,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (53,14,8,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (54,14,7,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (55,15,1,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (56,15,10,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (57,15,9,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (58,16,10,30);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (59,16,2,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (60,16,6,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (61,17,7,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (62,17,8,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (63,17,4,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (64,18,10,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (65,18,4,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (66,18,6,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (67,19,3,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (68,19,4,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (69,19,8,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (70,3,8,20);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (71,3,7,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (72,3,12,15);
INSERT INTO `sinergias_estilo` (`id_regla`, `id_estilo`, `id_familia`, `puntos_sumados`) VALUES (73,3,4,10);
/*!40000 ALTER TABLE `sinergias_estilo` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

